version: "3.9"

services:

  backend:
    build: ./apps/backend
    container_name: backend_auth
    ports:
      - "${BACKEND_PORT}:3001"
    volumes:
      - ./apps/backend:/app
      - backend_node_modules:/app/node_modules
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: postgres:16
    container_name: database_auth
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  backend_node_modules:
